# Generated by Django 6.0.3 on 2026-06-04 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('identificador_interno', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.cargo')),
                ('categoria_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.categoria_persona')),
                ('estado_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.estado_persona')),
                ('jefe_directo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='users.persona')),
                ('usuario_django', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
    ]
