# Generated by Django 6.0.3 on 2026-03-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.cargo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='categoria_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.categoria_persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.estado_persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='nivel_privilegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nivel_privilegio'),
        ),
    ]
