# Generated by Django 6.0.3 on 2026-06-23 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('users', '0003_alter_persona_email_alter_persona_usuario_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAltaGerencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('areas_supervision', models.ManyToManyField(blank=True, related_name='supervisores_gerencia', to='organization.area')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_gerencia', to='users.persona')),
            ],
            options={
                'verbose_name': 'Configuración Alta Gerencia',
                'verbose_name_plural': 'Configuraciones Alta Gerencia',
            },
        ),
    ]
