# Generated by Django 6.0.3 on 2026-06-04 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('valor', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_ioc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iocs', to='references.tipo_ioc')),
            ],
            options={
                'verbose_name': 'Indicador de Compromiso (IOC)',
                'verbose_name_plural': 'Indicadores de Compromiso (IOCs)',
            },
        ),
    ]
