# Generated by Django 6.0.3 on 2026-06-04 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IoC', '0001_initial'),
        ('organization', '0001_initial'),
        ('references', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('origen_incidente', models.TextField(blank=True)),
                ('recursos_afectados', models.TextField(blank=True)),
                ('contramedidas', models.TextField(blank=True)),
                ('otra_informacion', models.TextField(blank=True)),
                ('fecha_ocurrencia', models.DateTimeField(blank=True, null=True)),
                ('fecha_reportado', models.DateTimeField()),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_solucion', models.DateTimeField(blank=True, null=True)),
                ('alcance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alcance_incidente', to='references.alcance')),
                ('area_afectada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas_afectadas_incidente', to='organization.area')),
                ('especialista_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialistas_incidente', to='users.persona')),
                ('estado_incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estados_incidente', to='references.estado_incidente')),
                ('fuente_deteccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuentes_deteccion_incidente', to='references.fuente_deteccion')),
                ('impacto_incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impactos_incidente', to='references.impacto_incidente')),
                ('indicador_compromiso', models.ManyToManyField(blank=True, related_name='indicadores_compromiso_incidente', to='IoC.ioc')),
                ('intencionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intencionalidades_incidente', to='references.intencionalidad')),
                ('involucrados', models.ManyToManyField(blank=True, related_name='personas_involucradas_incidente', to='users.persona')),
                ('peligrosidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='niveles_peligrosidad_incidente', to='references.peligrosidad')),
                ('prioridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='niveles_prioridad_incidente', to='references.prioridad')),
                ('sistema_operativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sistemas_operativos_afectados_incidente', to='references.sistema_operativo')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias_incidente', to='references.subcategoria')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisores_incidente', to='users.persona')),
                ('tecnologia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tecnologias_afectadas_incidente', to='references.tecnologia')),
                ('tipo_incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_incidente', to='references.tipo_incidente')),
                ('vector_ataque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vectores_ataque_incidente', to='references.vector_ataque')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['fecha_reportado'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia_Incidente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('archivo', models.FileField(upload_to='evidencias_incidentes/')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='incidents.incidente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
