# Generated by Django 6.0.3 on 2026-04-05 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_persona_cargo_persona_categoria_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Incidente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Incidente',
                'verbose_name_plural': 'Tipos de Incidentes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('REP', 'Reportado'), ('ASI', 'Asignado'), ('INV', 'En Investigación'), ('CON', 'Contenido'), ('ERD', 'Eradicado'), ('RCV', 'Recuperación'), ('RES', 'Resuelto'), ('CER', 'Cerrado'), ('RCH', 'Rechazado')], default='REP', max_length=3)),
                ('impacto', models.CharField(choices=[('B', 'Bajo'), ('M', 'Medio'), ('A', 'Alto'), ('X', 'Extremo')], default='M', max_length=1)),
                ('fecha_deteccion', models.DateTimeField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('sistemas_afectados', models.TextField(blank=True)),
                ('acciones_tomadas', models.TextField(blank=True)),
                ('evidencias', models.TextField(blank=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_asignados', to='users.persona')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to='users.persona')),
                ('tipo_incidente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.tipo_incidente')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
