# Generated by Django 6.0.3 on 2026-07-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='incidents.incidente')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_incidente', to='users.persona')),
            ],
            options={
                'verbose_name': 'Mensaje del incidente',
                'verbose_name_plural': 'Mensajes del incidente',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
