# Generated by Django 6.0.3 on 2026-04-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='dependencia_afectada',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='incidente',
            name='entidad_afectada',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='incidente',
            name='origen_incidente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='otra_informacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='recursos_afectados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incidente',
            name='via_reporte',
            field=models.CharField(choices=[('TEL', 'Teléfono'), ('EMA', 'Correo Electrónico'), ('PRE', 'Presencial'), ('SIS', 'Sistema Automatizado'), ('OTR', 'Otro')], default='EMA', max_length=3),
        ),
    ]
