# Generated by Django 6.0.3 on 2026-03-21 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [ ]
