# Generated by Django 6.0.3 on 2026-06-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_persona',
            options={'ordering': ['name'], 'verbose_name': 'Categoria_Persona', 'verbose_name_plural': 'Categorias de Persona'},
        ),
        migrations.AlterModelOptions(
            name='estado_persona',
            options={'ordering': ['name'], 'verbose_name': 'Estado_Persona', 'verbose_name_plural': 'Estados de Persona'},
        ),
    ]
