# Generated by Django 6.0.3 on 2026-06-04 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('organization', '0001_initial'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('descripcion', models.TextField()),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('respuesta_supervisor', models.TextField(blank=True, null=True)),
                ('area_notificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_notificacion', to='organization.area')),
                ('asunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asuntos', to='references.asunto_notificacion')),
                ('estado_notificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_notificacion', to='references.estado_notificacion')),
                ('incidente_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_incidente', to='incidents.incidente')),
                ('usuario_notificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_notificadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia_Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('archivo', models.FileField(upload_to='evidencias_notificaciones/')),
                ('notificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='notifications.notificacion')),
            ],
            options={
                'verbose_name': 'Evidencia de la Notificación',
                'verbose_name_plural': 'Evidencias de la Notificación',
                'ordering': ['created'],
            },
        ),
    ]
