# Generated by Django 6.0.3 on 2026-06-18 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='area_notificacion',
            field=models.ForeignKey( on_delete=django.db.models.deletion.PROTECT, related_name='areas_notificacion', to='organization.area'),
        ),
    ]
